version: "3"
services:
  server:
    build: ./server
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    networks:
      - appnet
  client:
    build: ./client
    environment:
      - REACT_APP_SERVER_HOST=http://localhost:8000
    command: "yarn start"
    depends_on:
      - server
    ports:
      - 3000:3000
    networks:
      - appnet
networks:
  appnet:
